workspace:
  base: /drone
  path: src/github.com/uswitch/terraform-provider-segment

pipeline:
  build: 
    image: golang:1
    commands:
      - make build

  publish:
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - build/*
    when:
      event: tag