workspace:
  base: /drone
  path: src/github.com/uswitch/terraform-provider-segment

matrix:
  PLATFORM:
    - darwin.amd64
    - linux.386
    - linux.amd64
    - windows.386
    - windows.amd64

pipeline:
  build:
    image: golang:1-stretch
    commands:
      - . bin/set-platform.sh
      - make build

  publish:
    when:
      event: tag
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - build/*