name: CI

on:
  push:
  release:
    types: [created]

jobs:
  build:
    name: Build executables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64, 386]
        exclude:
          - os: darwin
            arch: 386
    steps:
      - name: Caching executables
        uses: actions/cache@v2
        with:
          path: |
            build
          key: ${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: make build
  
  release:
    name: Deploy executables to release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Caching executables
        uses: actions/cache@v2
        with:
          path: |
            build
          key: ${{ github.sha }}-
          restore-keys: ${{ github.sha }}-
      - run: ls build
