name: CI

on:
  push:
  release:
    types: [created]

jobs:
  build:
    name: Build executables
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64, 386]
        exclude:
          - os: darwin
            arch: 386
    env:
      OS: ${{ matrix.os }}
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Setting version from git
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Caching executables
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: ${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: VERSION=${{ steps.get_version.outputs.VERSION }} make build
  
  release:
    name: Deploy executables to release
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64, 386]
        exclude:
          - os: darwin
            arch: 386
    steps:
      - name: Retrieving cached executables
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: ${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}
      - run: ls build
