name: Pull request
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

jobs:

  # build code
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -v .

  # generate docs
  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        run: |
          go mod download

      - name: Generate docs
        run: |
          go generate
